name: Deploy SvelteKit Static Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./my-svelte-app
        run: npm install

      - name: Build SvelteKit static site
        working-directory: ./my-svelte-app
        run: npm run build

      - name: List build output (optional)
        working-directory: ./my-svelte-app
        run: ls -R ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-svelte-app/build